apiVersion: apps/v1
kind: Deployment
metadata:
  name: fykh
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fykh
  template:
    metadata:
      labels:
        app: fykh
    spec:
      containers:
      - image: okteto.dev/fykh:latest
        name: fykh
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "a498ee9f-1e7a-4419-a612-41013a9e8c36"
        - name: Vless_Path
          value: "/vlglk"
        - name: Vmess_UUID
          value: "a498ee9f-1e7a-4419-a612-41013a9e8c36"
        - name: Vmess_Path
          value: "/vmk3w"
        - name: Share_Path
          value: "/v2link"
